import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAcademyAdmin } from "../../../api/admin-access";
import { createCohort, setCohortRegistration } from "../../../api/cohort-actions";
import { ActionForm } from "../../../components/ActionForm";
import { AdminHeading } from "../../../components/admin/AdminUi";
import { inputClass } from "../../../components/ui";
export default async function CohortsPage() {
  await requireAcademyAdmin();
  const courses = await prisma.zakatAcademyCourse.findMany({ where: { isSimulation: false }, orderBy: { createdAt: "desc" }, include: { _count: { select: { enrollments: true, completionRecords: true } } } });
  return <><AdminHeading title="Angkatan Insan Academy" description="Setiap angkatan memiliki peserta, jadwal, nilai, dan sertifikat tersendiri. Hanya satu angkatan menerima pendaftaran web pada satu waktu." /><details className="mb-6 rounded-2xl bg-white p-5"><summary className="cursor-pointer font-semibold">Buat angkatan berikutnya</summary><ActionForm className="mt-5 max-w-xl" action={createCohort} label="Buat angkatan draft"><label>Nama angkatan<input name="title" required maxLength={191} className={inputClass} placeholder="Insan Academy — Angkatan 2" /></label><label>Salin materi dan soal dari<select name="sourceId" required className={inputClass}>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><p className="text-sm text-gray-500">Materi dan soal disalin. Jadwal absolut ujian dikosongkan dan ujian menjadi draft untuk pemeriksaan.</p></ActionForm></details><div className="space-y-4">{courses.map(course => <article key={course.id} className="rounded-2xl bg-white p-5"><h2 className="font-semibold">{course.title}</h2><p className="mt-2 text-sm text-gray-500">{course._count.enrollments}/{course.quota} peserta · {course.isPublished ? "Terpublikasi" : "Draft"} · Pendaftaran {course.registrationOpen ? "dibuka" : "ditutup"}</p><p className="mt-2 text-sm">Mulai: {course.startsAt ? `${course.startsAt.toLocaleString("id-ID", { timeZone: "Asia/Jakarta" })} WIB` : "Belum ditetapkan"}</p><div className="mt-4 flex flex-wrap items-center gap-4"><ActionForm action={setCohortRegistration.bind(null, course.id, !course.registrationOpen)} label={course.registrationOpen ? "Tutup pendaftaran" : "Buka pendaftaran"} /><Link href={`/admin/academy/program/${course.id}`} className="text-sm text-green-700">Kelola materi & soal →</Link><Link href="/admin/academy/pendaftaran" className="text-sm text-green-700">Peserta & jadwal →</Link></div></article>)}</div></>;
}
